### ISSUE TITLE
[BETA] Cooking Highlights

### ISSUE THREAD

**Issue by anindilla** [cookpad/community#11]
## **Summary :beer:**
Community tab will allow users to...
- **Browse** recent questions, tips, and cooksnaps from (1) recipes in their plan, (2) recipes they recently cooked, (3) their recipes, and (4) recent updates from the community
- **Create** their own question, tip, or cooksnap for (1) recipes in their plan, (2) recipes they recently cooked -- on top of a photo they snapped or picked from photo gallery
- **Engage** in conversations on their content as well as what has been posted by the community

## **Problems Being Solved :frowning:**
Will engaging in lively (fast, gets the job done & fun) activities around a recipe makes you want to cook more?

## **Solution Description :rocket:**
Flow is in this Figma: https://www.figma.com/file/LdtM7JgeoP8v0ie2V0IDPw/Indonesia-Sprint-October

## **Tasks🏗 :**

- [ ] https://github.com/cookpad/community/issues/12
- [ ] https://github.com/cookpad/community/issues/13
- [ ] https://github.com/cookpad/community/issues/14

## **Metrics Impacted :ok_hand:**
- Increased number of photo comments (primary metric)
- Increased number of replies to the comments
- Increased number of add to plan & cooked (secondary metric, non-vanity, direct impact to main OKR)

## **Beta Scenario :ballot_box_with_check:**
- Users can browse other people's contents (those who are in beta)
- Users can create their own content
- Users can respond to other people's contents

**Comment by tejanium** [comment]
Glad we're taking this further... 🎉 

We keep repeating this `questions, tips, and cooksnaps`, we need to come up with the name for this so we can have same terminology. It will make it easier for us devs to communicate with each other as well.

Note: please do not use existing terminology `Cooksnap` or `Photo Comment`

Some suggestions:
1. Meme
2. Post
3. Story
4. Status
5. Snap

**Comment by tejanium** [comment]
Is there any other way to discover `questions, tips, and cooksnaps`? for example, when people visit the recipe?

**Comment by waliahimanshu** [comment]
Should we also save the snapped image on the phone (if yes will be visible in the device gallery app) ?
